
export const allActionButton = [
    {
        id: 1,
        name: "Text",
        type: "text",
        data: {
            value: "",
            name: "placeholder",
            type: "text",
            html_type: "input",
            character_limit: "",
            required: false,
            disabled: true,
        },
    },
    {
        id: 2,
        name: "Date",
        type: "date",
        data: {
            value: "",
            name: "date",
            type: "date",
            html_type: "input",
            character_limit: "",
            required: false,
            disabled: true,
        },
    },
    // {
    //     id: 3,
    //     name: "Radio",
    //     type: "radio",
    //     data: {
    //         value: "",
    //         name: "placeholder",
    //         type: "radio",
    //         html_type: "input",
    //         required: false,
    //         disabled: true,
    //     },
    // },
    {
        id: 4,
        name: "Radio",
        type: "button",
        data: {
            value: "",
            name: "radio",
            type: "button",
            html_type: "button",
            character_limit: "",
            required: false,
            disabled: true,
        },
    },
    {
        id: 5,
        name: "Title",
        type: "text",
        data: {
            value: "",
            name: "placeholder",
            type: "text",
            character_limit: "",
            html_type: "label",
            required: false,
            disabled: true,
        },
    },
]

export const formFieldData = [
    {
        id: 1,
        title: "Regex",
        value: "",
        name: "regex",
        type: "text",
        required: false,
        disabled: false,
    },
    {
        id: 2,
        title: "Placeholder",
        value: "",
        name: "value",
        type: "text",
        required: false,
        disabled: true,
    },
    {
        id: 3,
        title: "Label",
        value: "",
        type: "text",
        name: "label",
        required: false,
        disabled: false,
    },
    {
        id: 4,
        title: "Character limit",
        value: "",
        type: "number",
        name: "character_limit",
        required: false,
        disabled: false,
    },
]